CREATE TABLE IF NOT EXISTS `User` (
  `UserId` int(11) NOT NULL AUTO_INCREMENT,
  `UserKey` varchar(36) NOT NULL,
  `UserName` varchar(50) NOT NULL,
  `FirstName` varchar(50) DEFAULT NULL,
  `LastName` varchar(50) DEFAULT NULL,
  `MiddleName` varchar(50) DEFAULT NULL,
  `DisplayName` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Email` varchar(50) DEFAULT NULL,
  `MobileCode` varchar(50) DEFAULT NULL,
  `MobileNumber` varchar(50) DEFAULT NULL,
  `LanguageId` int(11) NOT NULL DEFAULT 0,
  `TimeZoneId` int(11) NOT NULL DEFAULT 0,
  `ProfileImage` varchar(255) DEFAULT NULL,
  `ProfileAlternateImage` varchar(255) DEFAULT NULL,
  `CoverImage` varchar(255) DEFAULT NULL,
  `CoverAlternateImage` varchar(255) DEFAULT NULL,
  `IsCurator` tinyint(1) NOT NULL DEFAULT 0,
  `IsMerchant` tinyint(1) NOT NULL DEFAULT 0,
  `IsMm` tinyint(1) NOT NULL DEFAULT 0,
  `IsFeatured` tinyint(1) DEFAULT 0,
  `InventoryLocationId` int(11) DEFAULT 0,
  `DefaultUserAddressId` int(11) DEFAULT 0,
  `UserIdentificationId` int(11) DEFAULT 0,
  `ReferrerUserId` int(11) NOT NULL DEFAULT 0,
  `Hash` varchar(255) DEFAULT NULL,
  `Salt` varchar(50) DEFAULT NULL,
  `StatusId` int(11) NOT NULL DEFAULT 0,
  `StatusReasonCode` varchar(50) DEFAULT NULL,
  `GeoCountryId` int(11) NOT NULL DEFAULT 0,
  `GeoProvinceId` int(11) NOT NULL DEFAULT 0,
  `GeoCityId` int(11) NOT NULL DEFAULT 0,
  `Gender` varchar(50) DEFAULT NULL,
  `DateOfBirth` date DEFAULT NULL,
  `UserDescription` text CHARACTER SET utf8mb4 DEFAULT NULL,
  `SignupInviteCode` varchar(255) DEFAULT NULL,
  `ReferralInviteCode` varchar(255) DEFAULT NULL,
  `Priority` int(11) NOT NULL DEFAULT 0,
  `CommissionRate` decimal(10,4) DEFAULT NULL,
  `LastStatus` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `LastReset` timestamp(3) NULL DEFAULT NULL,
  `LastModified` timestamp(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  `LastLogin` timestamp NOT NULL DEFAULT current_timestamp(),
  `LastCreated` timestamp(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`UserId`),
  KEY `IDX_User_UserKey` (`UserKey`),
  KEY `IDX_User_Username` (`UserName`),
  KEY `IDX_User_LastModified` (`LastModified`),
  KEY `IDX_User_MobileCode_MobileNumber` (`MobileCode`,`MobileNumber`),
  KEY `IDX_User_MobileCode_MobileNumber_StatusId` (`MobileCode`,`MobileNumber`,`StatusId`),
  KEY `IDX_User_ReferralInviteCode` (`ReferralInviteCode`),
  KEY `IDX_User_LastCreated_StatusId` (`LastCreated`,`StatusId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;